/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:31f8940f-fe19-4e22-8baf-3c83a12093b6",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_nG1CR0URE",
    "aws_user_pools_web_client_id": "61t4sscsctufgiqki13o3te9j3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3esblvklozgenmefxdxjfvdumi.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kthvt57lb5aghmcbzwlo33ce4q",
    "aws_user_files_s3_bucket": "veda-elearning-store111227-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1",
    "aws_mobile_analytics_app_id": "b5aaecc213a8440eac5ca36f46e1e9f3",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
